### PR TITLE
Update KaTeX to 0.10.0-beta

### PR DESCRIPTION
**Pull request by bemeurer**

### CODE REVIEW

**Comment by euclio** [comment]
What does "beta" mean in this context? Is there a stable version we should be using instead?

**Comment by bemeurer** [comment]
Beta is just the [pre-release](https://github.com/Khan/KaTeX/releases). I chose to use 0.10.0-beta over 0.9.0 because the changeset for the 0.10.0 release is actually substantial, and has a lot of improvements to KaTeX. It shouldn't make any difference to most users that this is a beta release.

In any case, I can either:
1. Change the PR to 0.9.0
2. Commit to make a new PR when 0.10.0 gets released

What do you prefer?

**Comment by euclio** [comment]
I'd prefer to use 0.10, do you know when that might be released?

**Comment by bemeurer** [comment]
There is no ETA as far as I know, but my guess would be in 1-2 months?

**Comment by euclio** [comment]
Ok, I'll merge this now and we can update it again when it's released.

**Comment by bemeurer** [comment]
Cheers!

**Pull request merged**
